[2021-12-31 21:42:51,544] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 21:42:51,572] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 21:42:51,572] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:42:51,572] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 21:42:51,572] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:42:51,594] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 21:42:51,601] {standard_task_runner.py:52} INFO - Started process 8845 to run task
[2021-12-31 21:42:51,615] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmp12985os_', '--error-file', '/tmp/tmpl1j1t_oz']
[2021-12-31 21:42:51,616] {standard_task_runner.py:77} INFO - Job 45: Subtask tweet_extraction
[2021-12-31 21:42:51,705] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 21:42:53,213] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 21:42:53,214] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,215] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,215] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,215] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,215] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,218] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,218] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,219] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,219] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,219] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,219] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,219] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,220] {logging_mixin.py:109} INFO - Hello, Current Time:21:42:53 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 21:42:53,220] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 21:42:53,220] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 21:42:53,305] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T214251, end_date=20211231T214253
[2021-12-31 21:42:53,673] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 21:42:53,792] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-31 21:52:16,340] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 21:52:16,360] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 21:52:16,361] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:52:16,361] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 21:52:16,361] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:52:16,382] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 21:52:16,390] {standard_task_runner.py:52} INFO - Started process 9305 to run task
[2021-12-31 21:52:16,394] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmp9bwzqzzi', '--error-file', '/tmp/tmp4lra0gse']
[2021-12-31 21:52:16,395] {standard_task_runner.py:77} INFO - Job 63: Subtask tweet_extraction
[2021-12-31 21:52:16,459] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 21:52:16,508] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 21:52:16,509] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,509] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,510] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,510] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,510] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,510] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,510] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,510] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,510] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,510] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,510] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,510] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,510] {logging_mixin.py:109} INFO - Hello, Current Time:21:52:16 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 21:52:16,510] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 21:52:16,511] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strftime(ts)
AttributeError: module 'datetime' has no attribute 'strftime'
[2021-12-31 21:52:16,523] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T215216, end_date=20211231T215216
[2021-12-31 21:52:16,539] {standard_task_runner.py:92} ERROR - Failed to execute job 63 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strftime(ts)
AttributeError: module 'datetime' has no attribute 'strftime'
[2021-12-31 21:52:16,565] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 21:52:16,613] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 21:52:47,497] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 21:52:47,510] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 21:52:47,511] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:52:47,511] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 21:52:47,511] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:52:47,523] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 21:52:47,527] {standard_task_runner.py:52} INFO - Started process 9368 to run task
[2021-12-31 21:52:47,530] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpy0xw1e5x', '--error-file', '/tmp/tmp8k4ghkut']
[2021-12-31 21:52:47,531] {standard_task_runner.py:77} INFO - Job 75: Subtask tweet_extraction
[2021-12-31 21:52:47,583] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 21:52:47,635] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 21:52:47,636] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,636] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,636] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,636] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,636] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,637] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,637] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,637] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,637] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,637] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,637] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,637] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,637] {logging_mixin.py:109} INFO - Hello, Current Time:21:52:47 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 21:52:47,637] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 21:52:47,638] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strftime(ts)
AttributeError: module 'datetime' has no attribute 'strftime'
[2021-12-31 21:52:47,649] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T215247, end_date=20211231T215247
[2021-12-31 21:52:47,661] {standard_task_runner.py:92} ERROR - Failed to execute job 75 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strftime(ts)
AttributeError: module 'datetime' has no attribute 'strftime'
[2021-12-31 21:52:47,701] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 21:52:47,734] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 21:54:19,464] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 21:54:19,480] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 21:54:19,480] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:54:19,480] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 21:54:19,480] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:54:19,501] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 21:54:19,507] {standard_task_runner.py:52} INFO - Started process 9468 to run task
[2021-12-31 21:54:19,512] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmp22cv2efd', '--error-file', '/tmp/tmp9b0k2o32']
[2021-12-31 21:54:19,513] {standard_task_runner.py:77} INFO - Job 87: Subtask tweet_extraction
[2021-12-31 21:54:19,583] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 21:54:19,649] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 21:54:19,650] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,650] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,651] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,651] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,651] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,651] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,651] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,651] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,651] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,651] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,652] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,652] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,652] {logging_mixin.py:109} INFO - Hello, Current Time:21:54:19 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 21:54:19,652] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 21:54:19,652] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.datetime.strftime(ts)
TypeError: descriptor 'strftime' requires a 'datetime.date' object but received a 'str'
[2021-12-31 21:54:19,671] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T215419, end_date=20211231T215419
[2021-12-31 21:54:19,691] {standard_task_runner.py:92} ERROR - Failed to execute job 87 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.datetime.strftime(ts)
TypeError: descriptor 'strftime' requires a 'datetime.date' object but received a 'str'
[2021-12-31 21:54:19,724] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 21:54:19,779] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 21:59:28,261] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 21:59:28,285] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 21:59:28,286] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:59:28,286] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 21:59:28,286] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:59:28,312] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 21:59:28,323] {standard_task_runner.py:52} INFO - Started process 9733 to run task
[2021-12-31 21:59:28,331] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmptwmi95zo', '--error-file', '/tmp/tmpi6md078s']
[2021-12-31 21:59:28,332] {standard_task_runner.py:77} INFO - Job 100: Subtask tweet_extraction
[2021-12-31 21:59:28,454] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 21:59:28,547] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 21:59:28,548] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,548] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,548] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,548] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,549] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,549] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,549] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,549] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,549] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,549] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,549] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,549] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,549] {logging_mixin.py:109} INFO - Hello, Current Time:21:59:28 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 21:59:28,549] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 21:59:28,549] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strptime(ts, '%Y-%m-%dT%H:%M:%S%z')
AttributeError: module 'datetime' has no attribute 'strptime'
[2021-12-31 21:59:28,565] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T215928, end_date=20211231T215928
[2021-12-31 21:59:28,585] {standard_task_runner.py:92} ERROR - Failed to execute job 100 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strptime(ts, '%Y-%m-%dT%H:%M:%S%z')
AttributeError: module 'datetime' has no attribute 'strptime'
[2021-12-31 21:59:28,637] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 21:59:28,681] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 22:02:22,144] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 22:02:22,177] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 22:02:22,178] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:02:22,178] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 22:02:22,178] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:02:22,204] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 22:02:22,215] {standard_task_runner.py:52} INFO - Started process 9889 to run task
[2021-12-31 22:02:22,220] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmp6fwq_a0n', '--error-file', '/tmp/tmptotb_2y0']
[2021-12-31 22:02:22,221] {standard_task_runner.py:77} INFO - Job 112: Subtask tweet_extraction
[2021-12-31 22:02:22,345] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 22:02:22,522] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 22:02:22,526] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,526] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,527] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,527] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,527] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,528] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,528] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,528] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,528] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,535] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,535] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,536] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,536] {logging_mixin.py:109} INFO - Hello, Current Time:22:02:22 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 22:02:22,537] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 22:02:22,555] {logging_mixin.py:109} INFO - 2021-12-31 04:00:00+00:00
[2021-12-31 22:02:22,555] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 22:02:22,603] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T220222, end_date=20211231T220222
[2021-12-31 22:02:22,682] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 22:02:22,924] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 22:03:26,070] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 22:03:26,097] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 22:03:26,098] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:03:26,098] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 22:03:26,098] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:03:26,125] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 22:03:26,136] {standard_task_runner.py:52} INFO - Started process 9973 to run task
[2021-12-31 22:03:26,143] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpy76tzmdw', '--error-file', '/tmp/tmpqtgxfjlw']
[2021-12-31 22:03:26,145] {standard_task_runner.py:77} INFO - Job 124: Subtask tweet_extraction
[2021-12-31 22:03:26,251] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 22:03:26,360] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 22:03:26,363] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,364] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,364] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,364] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,364] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,364] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,364] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,365] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,365] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,365] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,365] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,365] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,365] {logging_mixin.py:109} INFO - Hello, Current Time:22:03:26 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 22:03:26,366] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 22:03:26,379] {logging_mixin.py:109} INFO - 2021-12-31 04:00:00+00:00
[2021-12-31 22:03:26,379] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 22:03:26,398] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T220326, end_date=20211231T220326
[2021-12-31 22:03:26,434] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 22:03:26,531] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-31 22:12:59,877] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 22:12:59,895] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 22:12:59,896] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:12:59,896] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 22:12:59,896] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:12:59,915] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 22:12:59,941] {standard_task_runner.py:52} INFO - Started process 10430 to run task
[2021-12-31 22:12:59,946] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmp7dl29nfy', '--error-file', '/tmp/tmpbldkszcp']
[2021-12-31 22:12:59,947] {standard_task_runner.py:77} INFO - Job 136: Subtask tweet_extraction
[2021-12-31 22:13:00,033] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 22:13:00,117] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 22:13:00,119] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,120] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,120] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,120] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,120] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,121] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,121] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,121] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,121] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,121] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,121] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,121] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,122] {logging_mixin.py:109} INFO - Hello, Current Time:22:13:00 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 22:13:00,122] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 22:13:00,132] {logging_mixin.py:109} INFO - start_time 2021-12-31T04:00:00Z
[2021-12-31 22:13:00,132] {logging_mixin.py:109} INFO - end_time 2021-12-31T04:10:00Z
[2021-12-31 22:13:00,133] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 22:13:00,152] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T221259, end_date=20211231T221300
[2021-12-31 22:13:00,199] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 22:13:00,239] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-31 22:16:30,169] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 22:16:30,181] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 22:16:30,181] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:16:30,181] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 22:16:30,182] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:16:30,196] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 22:16:30,201] {standard_task_runner.py:52} INFO - Started process 10618 to run task
[2021-12-31 22:16:30,204] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmp48fpzb9d', '--error-file', '/tmp/tmpsg0xf2zi']
[2021-12-31 22:16:30,204] {standard_task_runner.py:77} INFO - Job 148: Subtask tweet_extraction
[2021-12-31 22:16:30,258] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 22:16:30,310] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 22:16:30,312] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,312] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,312] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,312] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,312] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,312] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,312] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,313] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,313] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,313] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,313] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,313] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,313] {logging_mixin.py:109} INFO - Hello, Current Time:22:16:30 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 22:16:30,313] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 22:16:30,319] {logging_mixin.py:109} INFO - start_time 2021-12-31T04:00:00Z
[2021-12-31 22:16:30,319] {logging_mixin.py:109} INFO - end_time 2021-12-31T04:10:00Z
[2021-12-31 22:16:30,319] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 65, in extract
    response = requests.request("GET", url, headers=headers)
NameError: name 'requests' is not defined
[2021-12-31 22:16:30,331] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T221630, end_date=20211231T221630
[2021-12-31 22:16:30,342] {standard_task_runner.py:92} ERROR - Failed to execute job 148 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 65, in extract
    response = requests.request("GET", url, headers=headers)
NameError: name 'requests' is not defined
[2021-12-31 22:16:30,376] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 22:16:30,419] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 22:18:38,548] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 22:18:38,561] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 22:18:38,562] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:18:38,562] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 22:18:38,562] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:18:38,577] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 22:18:38,584] {standard_task_runner.py:52} INFO - Started process 10755 to run task
[2021-12-31 22:18:38,588] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmppf6z4wh0', '--error-file', '/tmp/tmpkhp2p4d5']
[2021-12-31 22:18:38,589] {standard_task_runner.py:77} INFO - Job 160: Subtask tweet_extraction
[2021-12-31 22:18:38,654] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 22:18:38,722] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 22:18:38,724] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,724] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,724] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,725] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,725] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,725] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,725] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,725] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,725] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,725] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,726] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,726] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:38,726] {logging_mixin.py:109} INFO - Hello, Current Time:22:18:38 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 22:18:38,726] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 22:18:38,735] {logging_mixin.py:109} INFO - start_time 2021-12-31T04:00:00Z
[2021-12-31 22:18:38,735] {logging_mixin.py:109} INFO - end_time 2021-12-31T04:10:00Z
[2021-12-31 22:18:39,239] {logging_mixin.py:109} INFO - {'data': [{'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568446869504', 'text': "STOP FUCKING GOING TO STARBUCKS TO GET A MEDICINE BALL BC YOU HAVE A SORE THROAT IF YOU KNOW YOU HAVE COVID OR EVEN IF YOU'RE NOT SURE, AND YES IT MATTERS IF YOU GO THROUGH THE DRIVE-THRU", 'author_id': '1164924322890297344'}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568404705282', 'text': 'RT @jennaaaayyy_: Free rapid COVID testing at 380 S 17th St. Richmond CA. No appt needed, stay safe ya’ll!', 'author_id': '797483317364826112', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476348153007800321'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568329388048', 'text': 'RT @CenterRotation: So I’m the exiting chief of surgery at my hospital. My two years of stupid meetings, babysitting disruptive surgeons, m…', 'author_id': '1454583445657686025', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476326358968119298'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568203431938', 'text': 'Quebec imposes COVID-19 curfew; Ontario limits eligibility for PCR tests amid Omicron surge - The Globe and Mail   https://t.co/bWEvGrc5Zg', 'author_id': '773485929969414148'}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567813308420', 'text': 'RT @official_kep1er: [News]\n\n케플러 샤오팅·마시로 코로나 완치..1월3일 데뷔 프로모션 재개\n\nAs members fully recovered from COVID-19, Kep1er will continue promotion…', 'author_id': '1452284405502840837', 'referenced_tweets': [{'type': 'retweeted', 'id': '1474960411250556935'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567800795136', 'text': '@kimiXu12 And that sucks :((( I want the pre Covid life back. :,)', 'author_id': '1393949294965657603', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476758929208004609'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567771541505', 'text': '@disclosetv We’ve been saying this since the onset of Covid. Catchup Fauci!\nThey are nearly 2 years behind on the narrative; I guess they couldn’t keep up the lie!', 'author_id': '1439581822871015432', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476697908045135872'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567746269187', 'text': 'RT @Desdemona_jna: No todo malestar es #Covid, 37 no es fiebre. Siguen existiendo las sinusitis alérgicas, las otitis y demás itis. Si tien…', 'author_id': '184331718', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476767412943036416'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567159169028', 'text': 'RT @lasleh: Participants who received a booster at least 5 months after a second dose of Pfizer vaccine had 90% lower mortality due to Covi…', 'author_id': '2166890976', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476471083159199747'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767566941073409', 'text': 'RT @chipfranklin: Should Tucker and Fox News be sued over COVID misinformation?', 'author_id': '280267313', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476587810341728270'}]}], 'includes': {'users': [{'location': 'Georgetown, TX', 'name': 'jaylen', 'id': '1164924322890297344', 'username': 'jaylenbrass', 'verified': False}, {'location': 'bay area', 'name': 'verónica', 'id': '797483317364826112', 'username': 'xeonniicc', 'verified': False}, {'name': 'Carolyn Holmes', 'id': '1454583445657686025', 'username': 'CarolynHolmes36', 'verified': False}, {'location': 'Hyderabad, India', 'name': 'Sarang Pokhare', 'id': '773485929969414148', 'username': 'sarang143u', 'verified': False}, {'location': 'she/her༄stan ot9!', 'name': 'zah☻', 'id': '1452284405502840837', 'username': 'ryuhiyyih', 'verified': False}, {'location': 'Subscribe↝', 'name': 'mint🧣', 'id': '1393949294965657603', 'username': 'yuyuniwerse', 'verified': False}, {'location': 'Texas, USA', 'name': 'CJM', 'id': '1439581822871015432', 'username': 'CJMNewf', 'verified': False}, {'location': 'Ciudad Autónoma de Buenos Aire', 'name': 'Xenia Soglian😺🐾SSB ⛵', 'id': '184331718', 'username': 'XeniaSailor', 'verified': False}, {'location': 'Helsinki, Finland', 'name': 'Linda Ahlblad', 'id': '2166890976', 'username': 'lindaahlblad', 'verified': False}, {'location': 'cape cod, ma', 'name': 'tina toran', 'id': '280267313', 'username': 'capecodtina', 'verified': False}], 'tweets': [{'created_at': '2021-12-30T00:23:23.000Z', 'id': '1476348153007800321', 'text': 'Free rapid COVID testing at 380 S 17th St. Richmond CA. No appt needed, stay safe ya’ll!', 'author_id': '803780388'}, {'created_at': '2021-12-29T22:56:47.000Z', 'id': '1476326358968119298', 'text': 'So I’m the exiting chief of surgery at my hospital. My two years of stupid meetings, babysitting disruptive surgeons, managing Covid staffing issues, etc has culminated in receiving a $50 gift card. That’s how out of touch hospitals are. SMH. #MedTwitter', 'author_id': '25959543'}, {'created_at': '2021-12-26T04:29:00.000Z', 'id': '1474960411250556935', 'text': '[News]\n\n케플러 샤오팅·마시로 코로나 완치..1월3일 데뷔 프로모션 재개\n\nAs members fully recovered from COVID-19, Kep1er will continue promotion for its January 3rd debut\n\n📎 https://t.co/TX8szPF3EP\n\n#Kep1er #케플러', 'author_id': '1448627067856179203'}, {'created_at': '2021-12-31T03:35:40.000Z', 'id': '1476758929208004609', 'text': '@yuyuniwerse We are stolen two years by epidemic', 'author_id': '1457215220381011968', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476749510940368900'}]}, {'created_at': '2021-12-30T23:33:11.000Z', 'id': '1476697908045135872', 'text': 'NEW - Dr. Fauci: "Important thing: Many of the children are hospitalized with Covid as opposed to because of Covid."\n\nhttps://t.co/g7NzfpKTsQ', 'author_id': '15392486'}, {'created_at': '2021-12-31T04:09:22.000Z', 'id': '1476767412943036416', 'text': 'No todo malestar es #Covid, 37 no es fiebre. Siguen existiendo las sinusitis alérgicas, las otitis y demás itis. Si tienen la suerte q tuve de buenos médicos q vieron más allá, todo es más fácil. Pataleen , no se queden con dudas... Nada... Eso.', 'author_id': '157830185'}, {'created_at': '2021-12-30T08:31:52.000Z', 'id': '1476471083159199747', 'text': 'Participants who received a booster at least 5 months after a second dose of Pfizer vaccine had 90% lower mortality due to Covid-19 than participants who did not receive a booster #covid19 #booster #mortality @NEJM https://t.co/uaBi6CjLJL', 'author_id': '729092700'}, {'created_at': '2021-12-30T16:15:42.000Z', 'id': '1476587810341728270', 'text': 'Should Tucker and Fox News be sued over COVID misinformation?', 'author_id': '48325671'}]}, 'meta': {'newest_id': '1476767568446869504', 'oldest_id': '1476767566941073409', 'result_count': 10, 'next_token': 'b26v89c19zqg8o3fpe17velabl0di743dno6sbhwy4ygt'}}
[2021-12-31 22:18:39,240] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 22:18:39,254] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T221838, end_date=20211231T221839
[2021-12-31 22:18:39,283] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 22:18:39,323] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-31 23:25:27,003] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 23:25:27,019] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 23:25:27,020] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:25:27,020] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 23:25:27,020] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:25:27,039] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 23:25:27,045] {standard_task_runner.py:52} INFO - Started process 1254 to run task
[2021-12-31 23:25:27,050] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpzoxfohpa', '--error-file', '/tmp/tmpkm_qw260']
[2021-12-31 23:25:27,051] {standard_task_runner.py:77} INFO - Job 174: Subtask tweet_extraction
[2021-12-31 23:25:27,096] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 23:25:27,133] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 23:25:27,134] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,134] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,135] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,135] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,135] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,135] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,135] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,135] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,135] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,135] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,135] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,136] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,136] {logging_mixin.py:109} INFO - Hello, Current Time:23:25:27 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 23:25:27,136] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 23:25:27,141] {logging_mixin.py:109} INFO - start_time 2021-12-31T04:00:00Z
[2021-12-31 23:25:27,141] {logging_mixin.py:109} INFO - end_time 2021-12-31T04:10:00Z
[2021-12-31 23:25:27,726] {logging_mixin.py:109} INFO - {'data': [{'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568446869504', 'text': "STOP FUCKING GOING TO STARBUCKS TO GET A MEDICINE BALL BC YOU HAVE A SORE THROAT IF YOU KNOW YOU HAVE COVID OR EVEN IF YOU'RE NOT SURE, AND YES IT MATTERS IF YOU GO THROUGH THE DRIVE-THRU", 'author_id': '1164924322890297344'}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568404705282', 'text': 'RT @jennaaaayyy_: Free rapid COVID testing at 380 S 17th St. Richmond CA. No appt needed, stay safe ya’ll!', 'author_id': '797483317364826112', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476348153007800321'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568329388048', 'text': 'RT @CenterRotation: So I’m the exiting chief of surgery at my hospital. My two years of stupid meetings, babysitting disruptive surgeons, m…', 'author_id': '1454583445657686025', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476326358968119298'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568203431938', 'text': 'Quebec imposes COVID-19 curfew; Ontario limits eligibility for PCR tests amid Omicron surge - The Globe and Mail   https://t.co/bWEvGrc5Zg', 'author_id': '773485929969414148'}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567813308420', 'text': 'RT @official_kep1er: [News]\n\n케플러 샤오팅·마시로 코로나 완치..1월3일 데뷔 프로모션 재개\n\nAs members fully recovered from COVID-19, Kep1er will continue promotion…', 'author_id': '1452284405502840837', 'referenced_tweets': [{'type': 'retweeted', 'id': '1474960411250556935'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567800795136', 'text': '@kimiXu12 And that sucks :((( I want the pre Covid life back. :,)', 'author_id': '1393949294965657603', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476758929208004609'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567771541505', 'text': '@disclosetv We’ve been saying this since the onset of Covid. Catchup Fauci!\nThey are nearly 2 years behind on the narrative; I guess they couldn’t keep up the lie!', 'author_id': '1439581822871015432', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476697908045135872'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567746269187', 'text': 'RT @Desdemona_jna: No todo malestar es #Covid, 37 no es fiebre. Siguen existiendo las sinusitis alérgicas, las otitis y demás itis. Si tien…', 'author_id': '184331718', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476767412943036416'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567159169028', 'text': 'RT @lasleh: Participants who received a booster at least 5 months after a second dose of Pfizer vaccine had 90% lower mortality due to Covi…', 'author_id': '2166890976', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476471083159199747'}]}, {'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767566941073409', 'text': 'RT @chipfranklin: Should Tucker and Fox News be sued over COVID misinformation?', 'author_id': '280267313', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476587810341728270'}]}], 'includes': {'users': [{'location': 'Georgetown, TX', 'name': 'jaylen', 'id': '1164924322890297344', 'username': 'jaylenbrass', 'verified': False}, {'location': 'bay area', 'name': 'verónica', 'id': '797483317364826112', 'username': 'xeonniicc', 'verified': False}, {'name': 'Carolyn Holmes', 'id': '1454583445657686025', 'username': 'CarolynHolmes36', 'verified': False}, {'location': 'Hyderabad, India', 'name': 'Sarang Pokhare', 'id': '773485929969414148', 'username': 'sarang143u', 'verified': False}, {'location': 'she/her༄stan ot9!', 'name': 'zah☻', 'id': '1452284405502840837', 'username': 'ryuhiyyih', 'verified': False}, {'location': 'Subscribe↝', 'name': 'mint🧣', 'id': '1393949294965657603', 'username': 'yuyuniwerse', 'verified': False}, {'location': 'Texas, USA', 'name': 'CJM', 'id': '1439581822871015432', 'username': 'CJMNewf', 'verified': False}, {'location': 'Ciudad Autónoma de Buenos Aire', 'name': 'Xenia Soglian😺🐾SSB ⛵', 'id': '184331718', 'username': 'XeniaSailor', 'verified': False}, {'location': 'Helsinki, Finland', 'name': 'Linda Ahlblad', 'id': '2166890976', 'username': 'lindaahlblad', 'verified': False}, {'location': 'cape cod, ma', 'name': 'tina toran', 'id': '280267313', 'username': 'capecodtina', 'verified': False}], 'tweets': [{'created_at': '2021-12-30T00:23:23.000Z', 'id': '1476348153007800321', 'text': 'Free rapid COVID testing at 380 S 17th St. Richmond CA. No appt needed, stay safe ya’ll!', 'author_id': '803780388'}, {'created_at': '2021-12-29T22:56:47.000Z', 'id': '1476326358968119298', 'text': 'So I’m the exiting chief of surgery at my hospital. My two years of stupid meetings, babysitting disruptive surgeons, managing Covid staffing issues, etc has culminated in receiving a $50 gift card. That’s how out of touch hospitals are. SMH. #MedTwitter', 'author_id': '25959543'}, {'created_at': '2021-12-26T04:29:00.000Z', 'id': '1474960411250556935', 'text': '[News]\n\n케플러 샤오팅·마시로 코로나 완치..1월3일 데뷔 프로모션 재개\n\nAs members fully recovered from COVID-19, Kep1er will continue promotion for its January 3rd debut\n\n📎 https://t.co/TX8szPF3EP\n\n#Kep1er #케플러', 'author_id': '1448627067856179203'}, {'created_at': '2021-12-31T03:35:40.000Z', 'id': '1476758929208004609', 'text': '@yuyuniwerse We are stolen two years by epidemic', 'author_id': '1457215220381011968', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476749510940368900'}]}, {'created_at': '2021-12-30T23:33:11.000Z', 'id': '1476697908045135872', 'text': 'NEW - Dr. Fauci: "Important thing: Many of the children are hospitalized with Covid as opposed to because of Covid."\n\nhttps://t.co/g7NzfpKTsQ', 'author_id': '15392486'}, {'created_at': '2021-12-31T04:09:22.000Z', 'id': '1476767412943036416', 'text': 'No todo malestar es #Covid, 37 no es fiebre. Siguen existiendo las sinusitis alérgicas, las otitis y demás itis. Si tienen la suerte q tuve de buenos médicos q vieron más allá, todo es más fácil. Pataleen , no se queden con dudas... Nada... Eso.', 'author_id': '157830185'}, {'created_at': '2021-12-30T08:31:52.000Z', 'id': '1476471083159199747', 'text': 'Participants who received a booster at least 5 months after a second dose of Pfizer vaccine had 90% lower mortality due to Covid-19 than participants who did not receive a booster #covid19 #booster #mortality @NEJM https://t.co/uaBi6CjLJL', 'author_id': '729092700'}, {'created_at': '2021-12-30T16:15:42.000Z', 'id': '1476587810341728270', 'text': 'Should Tucker and Fox News be sued over COVID misinformation?', 'author_id': '48325671'}]}, 'meta': {'newest_id': '1476767568446869504', 'oldest_id': '1476767566941073409', 'result_count': 10, 'next_token': 'b26v89c19zqg8o3fpe17velabl0di743dno6sbhwy4ygt'}}
[2021-12-31 23:25:27,727] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 72, in extract
    with open('plugins/data/{}'.format(filename), 'w') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'plugins/data/response_20211231T040000.json'
[2021-12-31 23:25:27,743] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T232527, end_date=20211231T232527
[2021-12-31 23:25:27,759] {standard_task_runner.py:92} ERROR - Failed to execute job 174 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 72, in extract
    with open('plugins/data/{}'.format(filename), 'w') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'plugins/data/response_20211231T040000.json'
[2021-12-31 23:25:27,784] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 23:25:27,918] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 23:26:57,948] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 23:26:57,968] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 23:26:57,968] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:26:57,968] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 23:26:57,968] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:26:57,982] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 23:26:57,987] {standard_task_runner.py:52} INFO - Started process 1353 to run task
[2021-12-31 23:26:57,991] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpca_z52hc', '--error-file', '/tmp/tmpmf5rf67g']
[2021-12-31 23:26:57,991] {standard_task_runner.py:77} INFO - Job 186: Subtask tweet_extraction
[2021-12-31 23:26:58,033] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 23:26:58,080] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 23:26:58,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,083] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,083] {logging_mixin.py:109} INFO - Hello, Current Time:23:26:58 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 23:26:58,083] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 23:26:58,088] {logging_mixin.py:109} INFO - start_time 2021-12-31T04:00:00Z
[2021-12-31 23:26:58,089] {logging_mixin.py:109} INFO - end_time 2021-12-31T04:10:00Z
[2021-12-31 23:26:58,411] {logging_mixin.py:109} INFO - {'data': [{'text': "STOP FUCKING GOING TO STARBUCKS TO GET A MEDICINE BALL BC YOU HAVE A SORE THROAT IF YOU KNOW YOU HAVE COVID OR EVEN IF YOU'RE NOT SURE, AND YES IT MATTERS IF YOU GO THROUGH THE DRIVE-THRU", 'author_id': '1164924322890297344', 'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568446869504'}, {'text': 'RT @jennaaaayyy_: Free rapid COVID testing at 380 S 17th St. Richmond CA. No appt needed, stay safe ya’ll!', 'author_id': '797483317364826112', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476348153007800321'}], 'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568404705282'}, {'text': 'RT @CenterRotation: So I’m the exiting chief of surgery at my hospital. My two years of stupid meetings, babysitting disruptive surgeons, m…', 'author_id': '1454583445657686025', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476326358968119298'}], 'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568329388048'}, {'text': 'Quebec imposes COVID-19 curfew; Ontario limits eligibility for PCR tests amid Omicron surge - The Globe and Mail   https://t.co/bWEvGrc5Zg', 'author_id': '773485929969414148', 'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767568203431938'}, {'text': 'RT @official_kep1er: [News]\n\n케플러 샤오팅·마시로 코로나 완치..1월3일 데뷔 프로모션 재개\n\nAs members fully recovered from COVID-19, Kep1er will continue promotion…', 'author_id': '1452284405502840837', 'referenced_tweets': [{'type': 'retweeted', 'id': '1474960411250556935'}], 'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567813308420'}, {'text': '@kimiXu12 And that sucks :((( I want the pre Covid life back. :,)', 'author_id': '1393949294965657603', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476758929208004609'}], 'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567800795136'}, {'text': '@disclosetv We’ve been saying this since the onset of Covid. Catchup Fauci!\nThey are nearly 2 years behind on the narrative; I guess they couldn’t keep up the lie!', 'author_id': '1439581822871015432', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476697908045135872'}], 'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567771541505'}, {'text': 'RT @Desdemona_jna: No todo malestar es #Covid, 37 no es fiebre. Siguen existiendo las sinusitis alérgicas, las otitis y demás itis. Si tien…', 'author_id': '184331718', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476767412943036416'}], 'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567746269187'}, {'text': 'RT @lasleh: Participants who received a booster at least 5 months after a second dose of Pfizer vaccine had 90% lower mortality due to Covi…', 'author_id': '2166890976', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476471083159199747'}], 'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767567159169028'}, {'text': 'RT @chipfranklin: Should Tucker and Fox News be sued over COVID misinformation?', 'author_id': '280267313', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476587810341728270'}], 'created_at': '2021-12-31T04:09:59.000Z', 'id': '1476767566941073409'}], 'includes': {'users': [{'id': '1164924322890297344', 'name': 'jaylen', 'verified': False, 'username': 'jaylenbrass', 'location': 'Georgetown, TX'}, {'id': '797483317364826112', 'name': 'verónica', 'verified': False, 'username': 'xeonniicc', 'location': 'bay area'}, {'id': '1454583445657686025', 'name': 'Carolyn Holmes', 'verified': False, 'username': 'CarolynHolmes36'}, {'id': '773485929969414148', 'name': 'Sarang Pokhare', 'verified': False, 'username': 'sarang143u', 'location': 'Hyderabad, India'}, {'id': '1452284405502840837', 'name': 'zah☻', 'verified': False, 'username': 'ryuhiyyih', 'location': 'she/her༄stan ot9!'}, {'id': '1393949294965657603', 'name': 'mint🧣', 'verified': False, 'username': 'yuyuniwerse', 'location': 'Subscribe↝'}, {'id': '1439581822871015432', 'name': 'CJM', 'verified': False, 'username': 'CJMNewf', 'location': 'Texas, USA'}, {'id': '184331718', 'name': 'Xenia Soglian😺🐾SSB ⛵', 'verified': False, 'username': 'XeniaSailor', 'location': 'Ciudad Autónoma de Buenos Aire'}, {'id': '2166890976', 'name': 'Linda Ahlblad', 'verified': False, 'username': 'lindaahlblad', 'location': 'Helsinki, Finland'}, {'id': '280267313', 'name': 'tina toran', 'verified': False, 'username': 'capecodtina', 'location': 'cape cod, ma'}], 'tweets': [{'text': 'Free rapid COVID testing at 380 S 17th St. Richmond CA. No appt needed, stay safe ya’ll!', 'author_id': '803780388', 'created_at': '2021-12-30T00:23:23.000Z', 'id': '1476348153007800321'}, {'text': 'So I’m the exiting chief of surgery at my hospital. My two years of stupid meetings, babysitting disruptive surgeons, managing Covid staffing issues, etc has culminated in receiving a $50 gift card. That’s how out of touch hospitals are. SMH. #MedTwitter', 'author_id': '25959543', 'created_at': '2021-12-29T22:56:47.000Z', 'id': '1476326358968119298'}, {'text': '[News]\n\n케플러 샤오팅·마시로 코로나 완치..1월3일 데뷔 프로모션 재개\n\nAs members fully recovered from COVID-19, Kep1er will continue promotion for its January 3rd debut\n\n📎 https://t.co/TX8szPF3EP\n\n#Kep1er #케플러', 'author_id': '1448627067856179203', 'created_at': '2021-12-26T04:29:00.000Z', 'id': '1474960411250556935'}, {'text': '@yuyuniwerse We are stolen two years by epidemic', 'author_id': '1457215220381011968', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476749510940368900'}], 'created_at': '2021-12-31T03:35:40.000Z', 'id': '1476758929208004609'}, {'text': 'NEW - Dr. Fauci: "Important thing: Many of the children are hospitalized with Covid as opposed to because of Covid."\n\nhttps://t.co/g7NzfpKTsQ', 'author_id': '15392486', 'created_at': '2021-12-30T23:33:11.000Z', 'id': '1476697908045135872'}, {'text': 'No todo malestar es #Covid, 37 no es fiebre. Siguen existiendo las sinusitis alérgicas, las otitis y demás itis. Si tienen la suerte q tuve de buenos médicos q vieron más allá, todo es más fácil. Pataleen , no se queden con dudas... Nada... Eso.', 'author_id': '157830185', 'created_at': '2021-12-31T04:09:22.000Z', 'id': '1476767412943036416'}, {'text': 'Participants who received a booster at least 5 months after a second dose of Pfizer vaccine had 90% lower mortality due to Covid-19 than participants who did not receive a booster #covid19 #booster #mortality @NEJM https://t.co/uaBi6CjLJL', 'author_id': '729092700', 'created_at': '2021-12-30T08:31:52.000Z', 'id': '1476471083159199747'}, {'text': 'Should Tucker and Fox News be sued over COVID misinformation?', 'author_id': '48325671', 'created_at': '2021-12-30T16:15:42.000Z', 'id': '1476587810341728270'}]}, 'meta': {'newest_id': '1476767568446869504', 'oldest_id': '1476767566941073409', 'result_count': 10, 'next_token': 'b26v89c19zqg8o3fpe17velabl0di743dno6sbhwy4ygt'}}
[2021-12-31 23:26:58,413] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 23:26:58,420] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T232657, end_date=20211231T232658
[2021-12-31 23:26:58,443] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 23:26:58,468] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-31 23:35:17,235] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 23:35:17,254] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [queued]>
[2021-12-31 23:35:17,254] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:35:17,254] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 23:35:17,254] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:35:17,273] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 04:00:00+00:00
[2021-12-31 23:35:17,281] {standard_task_runner.py:52} INFO - Started process 1778 to run task
[2021-12-31 23:35:17,288] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T04:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmprawpuahp', '--error-file', '/tmp/tmpgsbbe1q8']
[2021-12-31 23:35:17,290] {standard_task_runner.py:77} INFO - Job 198: Subtask tweet_extraction
[2021-12-31 23:35:17,430] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T04:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 23:35:17,532] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T04:00:00+00:00
[2021-12-31 23:35:17,534] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,534] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,534] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,534] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,534] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,535] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,535] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,535] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,535] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,535] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,535] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,535] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,535] {logging_mixin.py:109} INFO - Hello, Current Time:23:35:17 Execution time is 2021-12-31T04:00:00+00:00
[2021-12-31 23:35:17,535] {logging_mixin.py:109} INFO - 2021-12-31T04:00:00+00:00
[2021-12-31 23:35:17,545] {logging_mixin.py:109} INFO - start_time 2021-12-31T04:00:00Z
[2021-12-31 23:35:17,545] {logging_mixin.py:109} INFO - end_time 2021-12-31T04:10:00Z
[2021-12-31 23:35:18,014] {logging_mixin.py:109} INFO - {'data': [{'author_id': '1164924322890297344', 'created_at': '2021-12-31T04:09:59.000Z', 'text': "STOP FUCKING GOING TO STARBUCKS TO GET A MEDICINE BALL BC YOU HAVE A SORE THROAT IF YOU KNOW YOU HAVE COVID OR EVEN IF YOU'RE NOT SURE, AND YES IT MATTERS IF YOU GO THROUGH THE DRIVE-THRU", 'id': '1476767568446869504'}, {'author_id': '797483317364826112', 'created_at': '2021-12-31T04:09:59.000Z', 'text': 'RT @jennaaaayyy_: Free rapid COVID testing at 380 S 17th St. Richmond CA. No appt needed, stay safe ya’ll!', 'id': '1476767568404705282', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476348153007800321'}]}, {'author_id': '1454583445657686025', 'created_at': '2021-12-31T04:09:59.000Z', 'text': 'RT @CenterRotation: So I’m the exiting chief of surgery at my hospital. My two years of stupid meetings, babysitting disruptive surgeons, m…', 'id': '1476767568329388048', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476326358968119298'}]}, {'author_id': '773485929969414148', 'created_at': '2021-12-31T04:09:59.000Z', 'text': 'Quebec imposes COVID-19 curfew; Ontario limits eligibility for PCR tests amid Omicron surge - The Globe and Mail   https://t.co/bWEvGrc5Zg', 'id': '1476767568203431938'}, {'author_id': '1452284405502840837', 'created_at': '2021-12-31T04:09:59.000Z', 'text': 'RT @official_kep1er: [News]\n\n케플러 샤오팅·마시로 코로나 완치..1월3일 데뷔 프로모션 재개\n\nAs members fully recovered from COVID-19, Kep1er will continue promotion…', 'id': '1476767567813308420', 'referenced_tweets': [{'type': 'retweeted', 'id': '1474960411250556935'}]}, {'author_id': '1393949294965657603', 'created_at': '2021-12-31T04:09:59.000Z', 'text': '@kimiXu12 And that sucks :((( I want the pre Covid life back. :,)', 'id': '1476767567800795136', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476758929208004609'}]}, {'author_id': '1439581822871015432', 'created_at': '2021-12-31T04:09:59.000Z', 'text': '@disclosetv We’ve been saying this since the onset of Covid. Catchup Fauci!\nThey are nearly 2 years behind on the narrative; I guess they couldn’t keep up the lie!', 'id': '1476767567771541505', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476697908045135872'}]}, {'author_id': '184331718', 'created_at': '2021-12-31T04:09:59.000Z', 'text': 'RT @Desdemona_jna: No todo malestar es #Covid, 37 no es fiebre. Siguen existiendo las sinusitis alérgicas, las otitis y demás itis. Si tien…', 'id': '1476767567746269187', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476767412943036416'}]}, {'author_id': '2166890976', 'created_at': '2021-12-31T04:09:59.000Z', 'text': 'RT @lasleh: Participants who received a booster at least 5 months after a second dose of Pfizer vaccine had 90% lower mortality due to Covi…', 'id': '1476767567159169028', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476471083159199747'}]}, {'author_id': '280267313', 'created_at': '2021-12-31T04:09:59.000Z', 'text': 'RT @chipfranklin: Should Tucker and Fox News be sued over COVID misinformation?', 'id': '1476767566941073409', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476587810341728270'}]}], 'includes': {'users': [{'location': 'Georgetown, TX', 'verified': False, 'username': 'jaylenbrass', 'id': '1164924322890297344', 'name': 'jaylen'}, {'location': 'bay area', 'verified': False, 'username': 'xeonniicc', 'id': '797483317364826112', 'name': 'verónica'}, {'verified': False, 'username': 'CarolynHolmes36', 'id': '1454583445657686025', 'name': 'Carolyn Holmes'}, {'location': 'Hyderabad, India', 'verified': False, 'username': 'sarang143u', 'id': '773485929969414148', 'name': 'Sarang Pokhare'}, {'location': 'she/her༄stan ot9!', 'verified': False, 'username': 'ryuhiyyih', 'id': '1452284405502840837', 'name': 'zah☻'}, {'location': 'Subscribe↝', 'verified': False, 'username': 'yuyuniwerse', 'id': '1393949294965657603', 'name': 'mint🧣'}, {'location': 'Texas, USA', 'verified': False, 'username': 'CJMNewf', 'id': '1439581822871015432', 'name': 'CJM'}, {'location': 'Ciudad Autónoma de Buenos Aire', 'verified': False, 'username': 'XeniaSailor', 'id': '184331718', 'name': 'Xenia Soglian😺🐾SSB ⛵'}, {'location': 'Helsinki, Finland', 'verified': False, 'username': 'lindaahlblad', 'id': '2166890976', 'name': 'Linda Ahlblad'}, {'location': 'cape cod, ma', 'verified': False, 'username': 'capecodtina', 'id': '280267313', 'name': 'tina toran'}], 'tweets': [{'author_id': '803780388', 'created_at': '2021-12-30T00:23:23.000Z', 'text': 'Free rapid COVID testing at 380 S 17th St. Richmond CA. No appt needed, stay safe ya’ll!', 'id': '1476348153007800321'}, {'author_id': '25959543', 'created_at': '2021-12-29T22:56:47.000Z', 'text': 'So I’m the exiting chief of surgery at my hospital. My two years of stupid meetings, babysitting disruptive surgeons, managing Covid staffing issues, etc has culminated in receiving a $50 gift card. That’s how out of touch hospitals are. SMH. #MedTwitter', 'id': '1476326358968119298'}, {'author_id': '1448627067856179203', 'created_at': '2021-12-26T04:29:00.000Z', 'text': '[News]\n\n케플러 샤오팅·마시로 코로나 완치..1월3일 데뷔 프로모션 재개\n\nAs members fully recovered from COVID-19, Kep1er will continue promotion for its January 3rd debut\n\n📎 https://t.co/TX8szPF3EP\n\n#Kep1er #케플러', 'id': '1474960411250556935'}, {'author_id': '1457215220381011968', 'created_at': '2021-12-31T03:35:40.000Z', 'text': '@yuyuniwerse We are stolen two years by epidemic', 'id': '1476758929208004609', 'referenced_tweets': [{'type': 'replied_to', 'id': '1476749510940368900'}]}, {'author_id': '15392486', 'created_at': '2021-12-30T23:33:11.000Z', 'text': 'NEW - Dr. Fauci: "Important thing: Many of the children are hospitalized with Covid as opposed to because of Covid."\n\nhttps://t.co/g7NzfpKTsQ', 'id': '1476697908045135872'}, {'author_id': '157830185', 'created_at': '2021-12-31T04:09:22.000Z', 'text': 'No todo malestar es #Covid, 37 no es fiebre. Siguen existiendo las sinusitis alérgicas, las otitis y demás itis. Si tienen la suerte q tuve de buenos médicos q vieron más allá, todo es más fácil. Pataleen , no se queden con dudas... Nada... Eso.', 'id': '1476767412943036416'}, {'author_id': '729092700', 'created_at': '2021-12-30T08:31:52.000Z', 'text': 'Participants who received a booster at least 5 months after a second dose of Pfizer vaccine had 90% lower mortality due to Covid-19 than participants who did not receive a booster #covid19 #booster #mortality @NEJM https://t.co/uaBi6CjLJL', 'id': '1476471083159199747'}, {'author_id': '48325671', 'created_at': '2021-12-30T16:15:42.000Z', 'text': 'Should Tucker and Fox News be sued over COVID misinformation?', 'id': '1476587810341728270'}]}, 'meta': {'newest_id': '1476767568446869504', 'oldest_id': '1476767566941073409', 'result_count': 10, 'next_token': 'b26v89c19zqg8o3fpe17velabl0di743dno6sbhwy4ygt'}}
[2021-12-31 23:35:18,015] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 23:35:18,025] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T040000, start_date=20211231T233517, end_date=20211231T233518
[2021-12-31 23:35:18,047] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 23:35:18,080] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
