[2021-12-31 21:42:51,782] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 21:42:51,796] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 21:42:51,796] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:42:51,796] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 21:42:51,796] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:42:53,202] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 21:42:53,209] {standard_task_runner.py:52} INFO - Started process 8849 to run task
[2021-12-31 21:42:53,214] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpafb2n43z', '--error-file', '/tmp/tmpmtv13a77']
[2021-12-31 21:42:53,215] {standard_task_runner.py:77} INFO - Job 49: Subtask tweet_extraction
[2021-12-31 21:42:53,501] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 21:42:53,795] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 21:42:53,799] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,800] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,800] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,800] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,801] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,801] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,801] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,801] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,802] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,802] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,802] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,802] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:42:53,802] {logging_mixin.py:109} INFO - Hello, Current Time:21:42:53 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 21:42:53,802] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 21:42:53,802] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 21:42:53,839] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T214251, end_date=20211231T214253
[2021-12-31 21:42:53,921] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 21:42:53,971] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-31 21:52:16,419] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 21:52:16,434] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 21:52:16,435] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:52:16,435] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 21:52:16,435] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:52:16,450] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 21:52:16,455] {standard_task_runner.py:52} INFO - Started process 9306 to run task
[2021-12-31 21:52:16,458] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmp2maol1z3', '--error-file', '/tmp/tmpn1xncklg']
[2021-12-31 21:52:16,459] {standard_task_runner.py:77} INFO - Job 64: Subtask tweet_extraction
[2021-12-31 21:52:16,509] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 21:52:16,562] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 21:52:16,564] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,564] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,564] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,565] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,565] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,565] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,565] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,565] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,565] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,565] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,565] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,565] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:16,566] {logging_mixin.py:109} INFO - Hello, Current Time:21:52:16 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 21:52:16,566] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 21:52:16,566] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strftime(ts)
AttributeError: module 'datetime' has no attribute 'strftime'
[2021-12-31 21:52:16,579] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T215216, end_date=20211231T215216
[2021-12-31 21:52:16,598] {standard_task_runner.py:92} ERROR - Failed to execute job 64 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strftime(ts)
AttributeError: module 'datetime' has no attribute 'strftime'
[2021-12-31 21:52:16,630] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 21:52:16,668] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 21:52:47,647] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 21:52:47,657] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 21:52:47,658] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:52:47,658] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 21:52:47,658] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:52:47,669] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 21:52:47,673] {standard_task_runner.py:52} INFO - Started process 9369 to run task
[2021-12-31 21:52:47,676] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpf2q9y46t', '--error-file', '/tmp/tmpj5lcewih']
[2021-12-31 21:52:47,676] {standard_task_runner.py:77} INFO - Job 76: Subtask tweet_extraction
[2021-12-31 21:52:47,719] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 21:52:47,765] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 21:52:47,766] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,766] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,766] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,766] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,767] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,767] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,767] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,767] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,767] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,767] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,767] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,767] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:52:47,767] {logging_mixin.py:109} INFO - Hello, Current Time:21:52:47 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 21:52:47,767] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 21:52:47,767] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strftime(ts)
AttributeError: module 'datetime' has no attribute 'strftime'
[2021-12-31 21:52:47,778] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T215247, end_date=20211231T215247
[2021-12-31 21:52:47,788] {standard_task_runner.py:92} ERROR - Failed to execute job 76 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strftime(ts)
AttributeError: module 'datetime' has no attribute 'strftime'
[2021-12-31 21:52:47,808] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 21:52:47,850] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 21:54:19,633] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 21:54:19,649] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 21:54:19,649] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:54:19,649] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 21:54:19,649] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:54:19,668] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 21:54:19,677] {standard_task_runner.py:52} INFO - Started process 9469 to run task
[2021-12-31 21:54:19,681] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmp8zzppu9d', '--error-file', '/tmp/tmpsuvqn9le']
[2021-12-31 21:54:19,682] {standard_task_runner.py:77} INFO - Job 88: Subtask tweet_extraction
[2021-12-31 21:54:19,747] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 21:54:19,815] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 21:54:19,816] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,816] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,816] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,817] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,817] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,817] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,817] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,817] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,817] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,817] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,817] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,817] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:54:19,817] {logging_mixin.py:109} INFO - Hello, Current Time:21:54:19 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 21:54:19,818] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 21:54:19,818] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.datetime.strftime(ts)
TypeError: descriptor 'strftime' requires a 'datetime.date' object but received a 'str'
[2021-12-31 21:54:19,831] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T215419, end_date=20211231T215419
[2021-12-31 21:54:19,845] {standard_task_runner.py:92} ERROR - Failed to execute job 88 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.datetime.strftime(ts)
TypeError: descriptor 'strftime' requires a 'datetime.date' object but received a 'str'
[2021-12-31 21:54:19,854] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 21:54:19,889] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 21:59:28,642] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 21:59:28,656] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 21:59:28,656] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:59:28,656] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 21:59:28,657] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 21:59:28,669] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 21:59:28,674] {standard_task_runner.py:52} INFO - Started process 9734 to run task
[2021-12-31 21:59:28,677] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpqssmif9v', '--error-file', '/tmp/tmppavahjhc']
[2021-12-31 21:59:28,677] {standard_task_runner.py:77} INFO - Job 101: Subtask tweet_extraction
[2021-12-31 21:59:28,739] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 21:59:28,795] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 21:59:28,796] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,796] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,796] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,797] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,797] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,797] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,797] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,797] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,797] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,797] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,797] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,797] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 21:59:28,797] {logging_mixin.py:109} INFO - Hello, Current Time:21:59:28 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 21:59:28,797] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 21:59:28,797] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strptime(ts, '%Y-%m-%dT%H:%M:%S%z')
AttributeError: module 'datetime' has no attribute 'strptime'
[2021-12-31 21:59:28,810] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T215928, end_date=20211231T215928
[2021-12-31 21:59:28,822] {standard_task_runner.py:92} ERROR - Failed to execute job 101 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 59, in extract
    ts_datetime = datetime.strptime(ts, '%Y-%m-%dT%H:%M:%S%z')
AttributeError: module 'datetime' has no attribute 'strptime'
[2021-12-31 21:59:28,849] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 21:59:28,885] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 22:02:22,348] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 22:02:22,389] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 22:02:22,389] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:02:22,389] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 22:02:22,389] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:02:22,434] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 22:02:22,455] {standard_task_runner.py:52} INFO - Started process 9890 to run task
[2021-12-31 22:02:22,470] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpd69i77fr', '--error-file', '/tmp/tmp0k85xaw1']
[2021-12-31 22:02:22,472] {standard_task_runner.py:77} INFO - Job 113: Subtask tweet_extraction
[2021-12-31 22:02:22,677] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 22:02:22,835] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 22:02:22,839] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,839] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,839] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,839] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,840] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,840] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,840] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,840] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,840] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,840] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,841] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,841] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:02:22,841] {logging_mixin.py:109} INFO - Hello, Current Time:22:02:22 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 22:02:22,841] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 22:02:22,857] {logging_mixin.py:109} INFO - 2021-12-31 05:00:00+00:00
[2021-12-31 22:02:22,857] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 22:02:22,889] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T220222, end_date=20211231T220222
[2021-12-31 22:02:22,973] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 22:02:23,062] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-31 22:03:26,458] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 22:03:26,498] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 22:03:26,500] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:03:26,500] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 22:03:26,501] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:03:26,536] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 22:03:26,546] {standard_task_runner.py:52} INFO - Started process 9974 to run task
[2021-12-31 22:03:26,552] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmp164t9cw1', '--error-file', '/tmp/tmp_oo1jazn']
[2021-12-31 22:03:26,553] {standard_task_runner.py:77} INFO - Job 125: Subtask tweet_extraction
[2021-12-31 22:03:26,640] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 22:03:26,722] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 22:03:26,726] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,726] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,726] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,726] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,726] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,726] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,726] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,727] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,727] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,727] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,727] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,727] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:03:26,727] {logging_mixin.py:109} INFO - Hello, Current Time:22:03:26 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 22:03:26,727] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 22:03:26,735] {logging_mixin.py:109} INFO - 2021-12-31 05:00:00+00:00
[2021-12-31 22:03:26,735] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 22:03:26,749] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T220326, end_date=20211231T220326
[2021-12-31 22:03:26,804] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 22:03:26,844] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-31 22:13:00,239] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 22:13:00,251] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 22:13:00,251] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:13:00,251] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 22:13:00,251] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:13:00,263] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 22:13:00,269] {standard_task_runner.py:52} INFO - Started process 10433 to run task
[2021-12-31 22:13:00,272] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmp537mv3r8', '--error-file', '/tmp/tmpuqhttfe6']
[2021-12-31 22:13:00,273] {standard_task_runner.py:77} INFO - Job 137: Subtask tweet_extraction
[2021-12-31 22:13:00,322] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 22:13:00,370] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 22:13:00,371] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,371] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,371] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,371] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,371] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,371] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,371] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,371] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,372] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,372] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,372] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,372] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:13:00,372] {logging_mixin.py:109} INFO - Hello, Current Time:22:13:00 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 22:13:00,372] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 22:13:00,377] {logging_mixin.py:109} INFO - start_time 2021-12-31T05:00:00Z
[2021-12-31 22:13:00,378] {logging_mixin.py:109} INFO - end_time 2021-12-31T05:10:00Z
[2021-12-31 22:13:00,378] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 22:13:00,387] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T221300, end_date=20211231T221300
[2021-12-31 22:13:00,403] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 22:13:00,432] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-31 22:16:30,353] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 22:16:30,363] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 22:16:30,363] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:16:30,364] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 22:16:30,364] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:16:30,374] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 22:16:30,379] {standard_task_runner.py:52} INFO - Started process 10619 to run task
[2021-12-31 22:16:30,382] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpejjjyux6', '--error-file', '/tmp/tmpwpq9o702']
[2021-12-31 22:16:30,382] {standard_task_runner.py:77} INFO - Job 149: Subtask tweet_extraction
[2021-12-31 22:16:30,428] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 22:16:30,472] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 22:16:30,473] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,473] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:16:30,474] {logging_mixin.py:109} INFO - Hello, Current Time:22:16:30 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 22:16:30,474] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 22:16:30,480] {logging_mixin.py:109} INFO - start_time 2021-12-31T05:00:00Z
[2021-12-31 22:16:30,480] {logging_mixin.py:109} INFO - end_time 2021-12-31T05:10:00Z
[2021-12-31 22:16:30,480] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 65, in extract
    response = requests.request("GET", url, headers=headers)
NameError: name 'requests' is not defined
[2021-12-31 22:16:30,492] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T221630, end_date=20211231T221630
[2021-12-31 22:16:30,503] {standard_task_runner.py:92} ERROR - Failed to execute job 149 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 65, in extract
    response = requests.request("GET", url, headers=headers)
NameError: name 'requests' is not defined
[2021-12-31 22:16:30,514] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 22:16:30,577] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 22:18:39,184] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 22:18:39,197] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 22:18:39,197] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:18:39,197] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 22:18:39,197] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 22:18:39,212] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 22:18:39,218] {standard_task_runner.py:52} INFO - Started process 10758 to run task
[2021-12-31 22:18:39,221] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmp6zeoq1yd', '--error-file', '/tmp/tmp6lb6__km']
[2021-12-31 22:18:39,221] {standard_task_runner.py:77} INFO - Job 161: Subtask tweet_extraction
[2021-12-31 22:18:39,289] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 22:18:39,384] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 22:18:39,387] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,388] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,388] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,389] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,389] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,389] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,389] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,389] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,389] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,390] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,390] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,390] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 22:18:39,390] {logging_mixin.py:109} INFO - Hello, Current Time:22:18:39 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 22:18:39,390] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 22:18:39,401] {logging_mixin.py:109} INFO - start_time 2021-12-31T05:00:00Z
[2021-12-31 22:18:39,402] {logging_mixin.py:109} INFO - end_time 2021-12-31T05:10:00Z
[2021-12-31 22:18:39,791] {logging_mixin.py:109} INFO - {'data': [{'text': 'RT @MerlLems: plata, covid, y suerte en el amor nunca tuve', 'created_at': '2021-12-31T05:09:59.000Z', 'author_id': '4687651890', 'id': '1476782667920121858', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476229371308363777'}]}, {'text': 'RT @DrakeGatsby: “I’m here for a good time, not a long time” between Covid and climate change, you’re here for neither', 'created_at': '2021-12-31T05:09:59.000Z', 'author_id': '1001136081994174464', 'id': '1476782667291111429', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476545960767598592'}]}, {'text': 'RT @lavionline: quebec will really let someone positive for covid work but not someone wearing a hijab lol', 'created_at': '2021-12-31T05:09:59.000Z', 'author_id': '1043168694963200001', 'id': '1476782666972344334', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476108039468077057'}]}, {'text': 'Certificado de vacuna covid para TODO y TOD@S https://t.co/sHEot9KpA5', 'created_at': '2021-12-31T05:09:59.000Z', 'author_id': '1257280909', 'id': '1476782666783596545', 'referenced_tweets': [{'type': 'quoted', 'id': '1476277152068689920'}]}, {'text': 'RT @madeinmede: En conclusión, TODOS tienen covid pero unos dicen que es gripa y los otros ya se hicieron la prueba.', 'created_at': '2021-12-31T05:09:59.000Z', 'author_id': '1109237518501859328', 'id': '1476782666188038146', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476662756262793216'}]}, {'text': 'RT @ufrj: UFRJ ainda exigirá comprovação vacinal contra covid-19 para acesso a espaços da Universidade.\nhttps://t.co/I6GvkbPOEk\n\n#ufrj #vac…', 'created_at': '2021-12-31T05:09:59.000Z', 'author_id': '995076839390547979', 'id': '1476782665248485395', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476629208382246914'}]}, {'text': 'RT @NHSMillion: If everyone who has been grateful for NHS staff over the last two years followed and retweeted, we would reach a million in…', 'created_at': '2021-12-31T05:09:59.000Z', 'author_id': '704555058654883840', 'id': '1476782665047035904', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476611444640735238'}]}, {'text': 'RT @KLVeritas: COVID-19 vaccine mandates “have to be repealed” as the vaccines are “still in research” and “people cannot be mandated to pa…', 'created_at': '2021-12-31T05:09:59.000Z', 'author_id': '1122014915735089152', 'id': '1476782664908611585', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476333265548156928'}]}, {'text': 'RT @ClmBfQrTheStQrm: The latest VAERS covid vaccine ‘adverse event’ reports stats have been published. When we consider that maybe 1% of al…', 'created_at': '2021-12-31T05:09:59.000Z', 'author_id': '1378566968253513729', 'id': '1476782664447373330', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476282872583577610'}]}, {'text': 'RT @Julioac13: Polémico festejo de Fin de Año en la Afip: 160 contagiados con Covid. LN+', 'created_at': '2021-12-31T05:09:59.000Z', 'author_id': '1190492803366838272', 'id': '1476782664275447810', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476679233254612994'}]}], 'includes': {'users': [{'location': 'Rio Tercero', 'verified': False, 'username': 'juliettapereyra', 'name': "julie't", 'id': '4687651890'}, {'location': 'ur moms house', 'verified': False, 'username': 'appl3ofyoureye', 'name': 'Emily 💕', 'id': '1001136081994174464'}, {'location': 'Japan', 'verified': False, 'username': 'Nadashadow3', 'name': 'nαdaaaa', 'id': '1043168694963200001'}, {'verified': False, 'username': 'angel_canelones', 'name': '.', 'id': '1257280909'}, {'verified': False, 'username': 'wtfisthat23_', 'name': 'ᴳᵒᵐᵉⁿᵉᵃ☃️', 'id': '1109237518501859328'}, {'location': 'Saquarema, Brasil', 'verified': False, 'username': 'joaomarinx', 'name': 'Marins', 'id': '995076839390547979'}, {'location': 'Austral, Sydney', 'verified': False, 'username': 'traceyaustralia', 'name': 'Tracey', 'id': '704555058654883840'}, {'verified': False, 'username': 'Konsiderthis', 'name': 'LetFreedomRing', 'id': '1122014915735089152'}, {'location': 'NH', 'verified': False, 'username': 'CrystalSURFgrl', 'name': 'CrystalS.', 'id': '1378566968253513729'}, {'location': 'Ciudad Autónoma de Buenos Aire', 'verified': False, 'username': 'MoyanoMarite', 'name': 'Marité Moyano', 'id': '1190492803366838272'}], 'tweets': [{'text': 'plata, covid, y suerte en el amor nunca tuve', 'created_at': '2021-12-29T16:31:23.000Z', 'author_id': '2800469738', 'id': '1476229371308363777'}, {'text': '“I’m here for a good time, not a long time” between Covid and climate change, you’re here for neither', 'created_at': '2021-12-30T13:29:24.000Z', 'author_id': '1022128903236800512', 'id': '1476545960767598592'}, {'text': 'quebec will really let someone positive for covid work but not someone wearing a hijab lol', 'created_at': '2021-12-29T08:29:16.000Z', 'author_id': '4390003996', 'id': '1476108039468077057'}, {'text': 'Totalmente de acuerdo con empezar a pedir el certificado de vacunación para ir a lugares públicos. Poner en riesgo a otros por ser antivacunas no es justo. Eso no es perder la libertad. Perder la libertad es terminar internado o muerto por un par de egoístas.', 'created_at': '2021-12-29T19:41:15.000Z', 'author_id': '328312757', 'id': '1476277152068689920'}, {'text': 'En conclusión, TODOS tienen covid pero unos dicen que es gripa y los otros ya se hicieron la prueba.', 'created_at': '2021-12-30T21:13:30.000Z', 'author_id': '823595958525116417', 'id': '1476662756262793216'}, {'text': 'UFRJ ainda exigirá comprovação vacinal contra covid-19 para acesso a espaços da Universidade.\nhttps://t.co/I6GvkbPOEk\n\n#ufrj #vacina #covid19 https://t.co/Dd79rutNDn', 'created_at': '2021-12-30T19:00:12.000Z', 'author_id': '38733808', 'id': '1476629208382246914'}, {'text': 'If everyone who has been grateful for NHS staff over the last two years followed and retweeted, we would reach a million in no time.\n\nIt will only take a few seconds, and your support would really mean a lot to a huge number of people who continue to fight Covid-19. https://t.co/q3UHkk82Rc', 'created_at': '2021-12-30T17:49:37.000Z', 'author_id': '4882743003', 'id': '1476611444640735238'}, {'text': 'COVID-19 vaccine mandates “have to be repealed” as the vaccines are “still in research” and “people cannot be mandated to participate in research,” says\xa0@P_McCulloughMD \nhttps://t.co/ReBmW1uNfm', 'created_at': '2021-12-29T23:24:14.000Z', 'author_id': '1443993685209673729', 'id': '1476333265548156928'}, {'text': 'The latest VAERS covid vaccine ‘adverse event’ reports stats have been published. When we consider that maybe 1% of all reports make it to the list, you can add two zero’s onto each number, making for uncomfortable reading... https://t.co/MxpH1eKo2t', 'created_at': '2021-12-29T20:03:59.000Z', 'author_id': '1460273925020168197', 'id': '1476282872583577610'}, {'text': 'Polémico festejo de Fin de Año en la Afip: 160 contagiados con Covid. LN+', 'created_at': '2021-12-30T22:18:59.000Z', 'author_id': '1373021228043276290', 'id': '1476679233254612994'}]}, 'meta': {'newest_id': '1476782667920121858', 'oldest_id': '1476782664275447810', 'result_count': 10, 'next_token': 'b26v89c19zqg8o3fpe17velvouuzga5en99sdltam89kt'}}
[2021-12-31 22:18:39,791] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 22:18:39,804] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T221839, end_date=20211231T221839
[2021-12-31 22:18:39,839] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 22:18:39,874] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-31 23:25:26,883] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 23:25:26,908] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 23:25:26,908] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:25:26,908] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 23:25:26,908] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:25:26,927] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 23:25:26,935] {standard_task_runner.py:52} INFO - Started process 1253 to run task
[2021-12-31 23:25:26,942] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpz7tf8eg7', '--error-file', '/tmp/tmpd8t36c5i']
[2021-12-31 23:25:26,943] {standard_task_runner.py:77} INFO - Job 175: Subtask tweet_extraction
[2021-12-31 23:25:27,014] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 23:25:27,072] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 23:25:27,073] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,073] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,073] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,073] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,073] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,074] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,074] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,074] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,074] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,074] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,074] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,074] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:25:27,074] {logging_mixin.py:109} INFO - Hello, Current Time:23:25:27 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 23:25:27,074] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 23:25:27,080] {logging_mixin.py:109} INFO - start_time 2021-12-31T05:00:00Z
[2021-12-31 23:25:27,080] {logging_mixin.py:109} INFO - end_time 2021-12-31T05:10:00Z
[2021-12-31 23:25:27,726] {logging_mixin.py:109} INFO - {'data': [{'id': '1476782667920121858', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476229371308363777'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @MerlLems: plata, covid, y suerte en el amor nunca tuve', 'author_id': '4687651890'}, {'id': '1476782667291111429', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476545960767598592'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @DrakeGatsby: “I’m here for a good time, not a long time” between Covid and climate change, you’re here for neither', 'author_id': '1001136081994174464'}, {'id': '1476782666972344334', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476108039468077057'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @lavionline: quebec will really let someone positive for covid work but not someone wearing a hijab lol', 'author_id': '1043168694963200001'}, {'id': '1476782666783596545', 'referenced_tweets': [{'type': 'quoted', 'id': '1476277152068689920'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'Certificado de vacuna covid para TODO y TOD@S https://t.co/sHEot9KpA5', 'author_id': '1257280909'}, {'id': '1476782666188038146', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476662756262793216'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @madeinmede: En conclusión, TODOS tienen covid pero unos dicen que es gripa y los otros ya se hicieron la prueba.', 'author_id': '1109237518501859328'}, {'id': '1476782665248485395', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476629208382246914'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @ufrj: UFRJ ainda exigirá comprovação vacinal contra covid-19 para acesso a espaços da Universidade.\nhttps://t.co/I6GvkbPOEk\n\n#ufrj #vac…', 'author_id': '995076839390547979'}, {'id': '1476782665047035904', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476611444640735238'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @NHSMillion: If everyone who has been grateful for NHS staff over the last two years followed and retweeted, we would reach a million in…', 'author_id': '704555058654883840'}, {'id': '1476782664908611585', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476333265548156928'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @KLVeritas: COVID-19 vaccine mandates “have to be repealed” as the vaccines are “still in research” and “people cannot be mandated to pa…', 'author_id': '1122014915735089152'}, {'id': '1476782664447373330', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476282872583577610'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @ClmBfQrTheStQrm: The latest VAERS covid vaccine ‘adverse event’ reports stats have been published. When we consider that maybe 1% of al…', 'author_id': '1378566968253513729'}, {'id': '1476782664275447810', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476679233254612994'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @Julioac13: Polémico festejo de Fin de Año en la Afip: 160 contagiados con Covid. LN+', 'author_id': '1190492803366838272'}], 'includes': {'users': [{'name': "julie't", 'username': 'juliettapereyra', 'location': 'Rio Tercero', 'id': '4687651890', 'verified': False}, {'name': 'Emily 💕', 'username': 'appl3ofyoureye', 'location': 'ur moms house', 'id': '1001136081994174464', 'verified': False}, {'name': 'nαdaaaa', 'username': 'Nadashadow3', 'location': 'Japan', 'id': '1043168694963200001', 'verified': False}, {'name': '.', 'username': 'angel_canelones', 'id': '1257280909', 'verified': False}, {'name': 'ᴳᵒᵐᵉⁿᵉᵃ☃️', 'username': 'wtfisthat23_', 'id': '1109237518501859328', 'verified': False}, {'name': 'Marins', 'username': 'joaomarinx', 'location': 'Saquarema, Brasil', 'id': '995076839390547979', 'verified': False}, {'name': 'Tracey', 'username': 'traceyaustralia', 'location': 'Austral, Sydney', 'id': '704555058654883840', 'verified': False}, {'name': 'LetFreedomRing', 'username': 'Konsiderthis', 'id': '1122014915735089152', 'verified': False}, {'name': 'CrystalS.', 'username': 'CrystalSURFgrl', 'location': 'NH', 'id': '1378566968253513729', 'verified': False}, {'name': 'Marité Moyano', 'username': 'MoyanoMarite', 'location': 'Ciudad Autónoma de Buenos Aire', 'id': '1190492803366838272', 'verified': False}], 'tweets': [{'id': '1476229371308363777', 'created_at': '2021-12-29T16:31:23.000Z', 'text': 'plata, covid, y suerte en el amor nunca tuve', 'author_id': '2800469738'}, {'id': '1476545960767598592', 'created_at': '2021-12-30T13:29:24.000Z', 'text': '“I’m here for a good time, not a long time” between Covid and climate change, you’re here for neither', 'author_id': '1022128903236800512'}, {'id': '1476108039468077057', 'created_at': '2021-12-29T08:29:16.000Z', 'text': 'quebec will really let someone positive for covid work but not someone wearing a hijab lol', 'author_id': '4390003996'}, {'id': '1476277152068689920', 'created_at': '2021-12-29T19:41:15.000Z', 'text': 'Totalmente de acuerdo con empezar a pedir el certificado de vacunación para ir a lugares públicos. Poner en riesgo a otros por ser antivacunas no es justo. Eso no es perder la libertad. Perder la libertad es terminar internado o muerto por un par de egoístas.', 'author_id': '328312757'}, {'id': '1476662756262793216', 'created_at': '2021-12-30T21:13:30.000Z', 'text': 'En conclusión, TODOS tienen covid pero unos dicen que es gripa y los otros ya se hicieron la prueba.', 'author_id': '823595958525116417'}, {'id': '1476629208382246914', 'created_at': '2021-12-30T19:00:12.000Z', 'text': 'UFRJ ainda exigirá comprovação vacinal contra covid-19 para acesso a espaços da Universidade.\nhttps://t.co/I6GvkbPOEk\n\n#ufrj #vacina #covid19 https://t.co/Dd79rutNDn', 'author_id': '38733808'}, {'id': '1476611444640735238', 'created_at': '2021-12-30T17:49:37.000Z', 'text': 'If everyone who has been grateful for NHS staff over the last two years followed and retweeted, we would reach a million in no time.\n\nIt will only take a few seconds, and your support would really mean a lot to a huge number of people who continue to fight Covid-19. https://t.co/q3UHkk82Rc', 'author_id': '4882743003'}, {'id': '1476333265548156928', 'created_at': '2021-12-29T23:24:14.000Z', 'text': 'COVID-19 vaccine mandates “have to be repealed” as the vaccines are “still in research” and “people cannot be mandated to participate in research,” says\xa0@P_McCulloughMD \nhttps://t.co/ReBmW1uNfm', 'author_id': '1443993685209673729'}, {'id': '1476282872583577610', 'created_at': '2021-12-29T20:03:59.000Z', 'text': 'The latest VAERS covid vaccine ‘adverse event’ reports stats have been published. When we consider that maybe 1% of all reports make it to the list, you can add two zero’s onto each number, making for uncomfortable reading... https://t.co/MxpH1eKo2t', 'author_id': '1460273925020168197'}, {'id': '1476679233254612994', 'created_at': '2021-12-30T22:18:59.000Z', 'text': 'Polémico festejo de Fin de Año en la Afip: 160 contagiados con Covid. LN+', 'author_id': '1373021228043276290'}]}, 'meta': {'newest_id': '1476782667920121858', 'oldest_id': '1476782664275447810', 'result_count': 10, 'next_token': 'b26v89c19zqg8o3fpe17velvouuzga5en99sdltam89kt'}}
[2021-12-31 23:25:27,727] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 72, in extract
    with open('plugins/data/{}'.format(filename), 'w') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'plugins/data/response_20211231T050000.json'
[2021-12-31 23:25:27,742] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T232526, end_date=20211231T232527
[2021-12-31 23:25:27,766] {standard_task_runner.py:92} ERROR - Failed to execute job 175 for task tweet_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_redshift.py", line 72, in extract
    with open('plugins/data/{}'.format(filename), 'w') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'plugins/data/response_20211231T050000.json'
[2021-12-31 23:25:27,793] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-31 23:25:27,913] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-31 23:26:58,130] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 23:26:58,140] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 23:26:58,140] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:26:58,140] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 23:26:58,140] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:26:58,151] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 23:26:58,155] {standard_task_runner.py:52} INFO - Started process 1354 to run task
[2021-12-31 23:26:58,160] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpfzwlsdcx', '--error-file', '/tmp/tmphzyalh7t']
[2021-12-31 23:26:58,161] {standard_task_runner.py:77} INFO - Job 187: Subtask tweet_extraction
[2021-12-31 23:26:58,203] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 23:26:58,240] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 23:26:58,241] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,241] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,241] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,241] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,241] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,241] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,242] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,242] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,242] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,242] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,242] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,242] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:26:58,242] {logging_mixin.py:109} INFO - Hello, Current Time:23:26:58 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 23:26:58,242] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 23:26:58,247] {logging_mixin.py:109} INFO - start_time 2021-12-31T05:00:00Z
[2021-12-31 23:26:58,247] {logging_mixin.py:109} INFO - end_time 2021-12-31T05:10:00Z
[2021-12-31 23:26:58,808] {logging_mixin.py:109} INFO - {'data': [{'author_id': '4687651890', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476229371308363777'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @MerlLems: plata, covid, y suerte en el amor nunca tuve', 'id': '1476782667920121858'}, {'author_id': '1001136081994174464', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476545960767598592'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @DrakeGatsby: “I’m here for a good time, not a long time” between Covid and climate change, you’re here for neither', 'id': '1476782667291111429'}, {'author_id': '1043168694963200001', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476108039468077057'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @lavionline: quebec will really let someone positive for covid work but not someone wearing a hijab lol', 'id': '1476782666972344334'}, {'author_id': '1257280909', 'referenced_tweets': [{'type': 'quoted', 'id': '1476277152068689920'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'Certificado de vacuna covid para TODO y TOD@S https://t.co/sHEot9KpA5', 'id': '1476782666783596545'}, {'author_id': '1109237518501859328', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476662756262793216'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @madeinmede: En conclusión, TODOS tienen covid pero unos dicen que es gripa y los otros ya se hicieron la prueba.', 'id': '1476782666188038146'}, {'author_id': '995076839390547979', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476629208382246914'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @ufrj: UFRJ ainda exigirá comprovação vacinal contra covid-19 para acesso a espaços da Universidade.\nhttps://t.co/I6GvkbPOEk\n\n#ufrj #vac…', 'id': '1476782665248485395'}, {'author_id': '704555058654883840', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476611444640735238'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @NHSMillion: If everyone who has been grateful for NHS staff over the last two years followed and retweeted, we would reach a million in…', 'id': '1476782665047035904'}, {'author_id': '1122014915735089152', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476333265548156928'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @KLVeritas: COVID-19 vaccine mandates “have to be repealed” as the vaccines are “still in research” and “people cannot be mandated to pa…', 'id': '1476782664908611585'}, {'author_id': '1378566968253513729', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476282872583577610'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @ClmBfQrTheStQrm: The latest VAERS covid vaccine ‘adverse event’ reports stats have been published. When we consider that maybe 1% of al…', 'id': '1476782664447373330'}, {'author_id': '1190492803366838272', 'referenced_tweets': [{'type': 'retweeted', 'id': '1476679233254612994'}], 'created_at': '2021-12-31T05:09:59.000Z', 'text': 'RT @Julioac13: Polémico festejo de Fin de Año en la Afip: 160 contagiados con Covid. LN+', 'id': '1476782664275447810'}], 'includes': {'users': [{'id': '4687651890', 'username': 'juliettapereyra', 'name': "julie't", 'location': 'Rio Tercero', 'verified': False}, {'id': '1001136081994174464', 'username': 'appl3ofyoureye', 'name': 'Emily 💕', 'location': 'ur moms house', 'verified': False}, {'id': '1043168694963200001', 'username': 'Nadashadow3', 'name': 'nαdaaaa', 'location': 'Japan', 'verified': False}, {'id': '1257280909', 'username': 'angel_canelones', 'name': '.', 'verified': False}, {'id': '1109237518501859328', 'username': 'wtfisthat23_', 'name': 'ᴳᵒᵐᵉⁿᵉᵃ☃️', 'verified': False}, {'id': '995076839390547979', 'username': 'joaomarinx', 'name': 'Marins', 'location': 'Saquarema, Brasil', 'verified': False}, {'id': '704555058654883840', 'username': 'traceyaustralia', 'name': 'Tracey', 'location': 'Austral, Sydney', 'verified': False}, {'id': '1122014915735089152', 'username': 'Konsiderthis', 'name': 'LetFreedomRing', 'verified': False}, {'id': '1378566968253513729', 'username': 'CrystalSURFgrl', 'name': 'CrystalS.', 'location': 'NH', 'verified': False}, {'id': '1190492803366838272', 'username': 'MoyanoMarite', 'name': 'Marité Moyano', 'location': 'Ciudad Autónoma de Buenos Aire', 'verified': False}], 'tweets': [{'author_id': '2800469738', 'created_at': '2021-12-29T16:31:23.000Z', 'text': 'plata, covid, y suerte en el amor nunca tuve', 'id': '1476229371308363777'}, {'author_id': '1022128903236800512', 'created_at': '2021-12-30T13:29:24.000Z', 'text': '“I’m here for a good time, not a long time” between Covid and climate change, you’re here for neither', 'id': '1476545960767598592'}, {'author_id': '4390003996', 'created_at': '2021-12-29T08:29:16.000Z', 'text': 'quebec will really let someone positive for covid work but not someone wearing a hijab lol', 'id': '1476108039468077057'}, {'author_id': '328312757', 'created_at': '2021-12-29T19:41:15.000Z', 'text': 'Totalmente de acuerdo con empezar a pedir el certificado de vacunación para ir a lugares públicos. Poner en riesgo a otros por ser antivacunas no es justo. Eso no es perder la libertad. Perder la libertad es terminar internado o muerto por un par de egoístas.', 'id': '1476277152068689920'}, {'author_id': '823595958525116417', 'created_at': '2021-12-30T21:13:30.000Z', 'text': 'En conclusión, TODOS tienen covid pero unos dicen que es gripa y los otros ya se hicieron la prueba.', 'id': '1476662756262793216'}, {'author_id': '38733808', 'created_at': '2021-12-30T19:00:12.000Z', 'text': 'UFRJ ainda exigirá comprovação vacinal contra covid-19 para acesso a espaços da Universidade.\nhttps://t.co/I6GvkbPOEk\n\n#ufrj #vacina #covid19 https://t.co/Dd79rutNDn', 'id': '1476629208382246914'}, {'author_id': '4882743003', 'created_at': '2021-12-30T17:49:37.000Z', 'text': 'If everyone who has been grateful for NHS staff over the last two years followed and retweeted, we would reach a million in no time.\n\nIt will only take a few seconds, and your support would really mean a lot to a huge number of people who continue to fight Covid-19. https://t.co/q3UHkk82Rc', 'id': '1476611444640735238'}, {'author_id': '1443993685209673729', 'created_at': '2021-12-29T23:24:14.000Z', 'text': 'COVID-19 vaccine mandates “have to be repealed” as the vaccines are “still in research” and “people cannot be mandated to participate in research,” says\xa0@P_McCulloughMD \nhttps://t.co/ReBmW1uNfm', 'id': '1476333265548156928'}, {'author_id': '1460273925020168197', 'created_at': '2021-12-29T20:03:59.000Z', 'text': 'The latest VAERS covid vaccine ‘adverse event’ reports stats have been published. When we consider that maybe 1% of all reports make it to the list, you can add two zero’s onto each number, making for uncomfortable reading... https://t.co/MxpH1eKo2t', 'id': '1476282872583577610'}, {'author_id': '1373021228043276290', 'created_at': '2021-12-30T22:18:59.000Z', 'text': 'Polémico festejo de Fin de Año en la Afip: 160 contagiados con Covid. LN+', 'id': '1476679233254612994'}]}, 'meta': {'newest_id': '1476782667920121858', 'oldest_id': '1476782664275447810', 'result_count': 10, 'next_token': 'b26v89c19zqg8o3fpe17velvouuzga5en99sdltam89kt'}}
[2021-12-31 23:26:58,809] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 23:26:58,913] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T232658, end_date=20211231T232658
[2021-12-31 23:26:58,975] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 23:26:59,004] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-31 23:35:17,476] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 23:35:17,501] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [queued]>
[2021-12-31 23:35:17,502] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:35:17,502] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2021-12-31 23:35:17,502] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 23:35:17,515] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): tweet_extraction> on 2021-12-31 05:00:00+00:00
[2021-12-31 23:35:17,522] {standard_task_runner.py:52} INFO - Started process 1779 to run task
[2021-12-31 23:35:17,526] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_dimensions', 'tweet_extraction', 'scheduled__2021-12-31T05:00:00+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/load_redshift.py', '--cfg-path', '/tmp/tmpkr1lrrhg', '--error-file', '/tmp/tmpktw77kjt']
[2021-12-31 23:35:17,527] {standard_task_runner.py:77} INFO - Job 199: Subtask tweet_extraction
[2021-12-31 23:35:17,593] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dimensions.tweet_extraction scheduled__2021-12-31T05:00:00+00:00 [running]> on host 87b5e846a243
[2021-12-31 23:35:17,655] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=test_owner
AIRFLOW_CTX_DAG_ID=load_dimensions
AIRFLOW_CTX_TASK_ID=tweet_extraction
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T05:00:00+00:00
[2021-12-31 23:35:17,656] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,656] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,657] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,657] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,657] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,657] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,657] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,657] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,657] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,657] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,658] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,658] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2021-12-31 23:35:17,658] {logging_mixin.py:109} INFO - Hello, Current Time:23:35:17 Execution time is 2021-12-31T05:00:00+00:00
[2021-12-31 23:35:17,658] {logging_mixin.py:109} INFO - 2021-12-31T05:00:00+00:00
[2021-12-31 23:35:17,667] {logging_mixin.py:109} INFO - start_time 2021-12-31T05:00:00Z
[2021-12-31 23:35:17,667] {logging_mixin.py:109} INFO - end_time 2021-12-31T05:10:00Z
[2021-12-31 23:35:18,180] {logging_mixin.py:109} INFO - {'data': [{'referenced_tweets': [{'type': 'retweeted', 'id': '1476229371308363777'}], 'text': 'RT @MerlLems: plata, covid, y suerte en el amor nunca tuve', 'author_id': '4687651890', 'created_at': '2021-12-31T05:09:59.000Z', 'id': '1476782667920121858'}, {'referenced_tweets': [{'type': 'retweeted', 'id': '1476545960767598592'}], 'text': 'RT @DrakeGatsby: “I’m here for a good time, not a long time” between Covid and climate change, you’re here for neither', 'author_id': '1001136081994174464', 'created_at': '2021-12-31T05:09:59.000Z', 'id': '1476782667291111429'}, {'referenced_tweets': [{'type': 'retweeted', 'id': '1476108039468077057'}], 'text': 'RT @lavionline: quebec will really let someone positive for covid work but not someone wearing a hijab lol', 'author_id': '1043168694963200001', 'created_at': '2021-12-31T05:09:59.000Z', 'id': '1476782666972344334'}, {'referenced_tweets': [{'type': 'quoted', 'id': '1476277152068689920'}], 'text': 'Certificado de vacuna covid para TODO y TOD@S https://t.co/sHEot9KpA5', 'author_id': '1257280909', 'created_at': '2021-12-31T05:09:59.000Z', 'id': '1476782666783596545'}, {'referenced_tweets': [{'type': 'retweeted', 'id': '1476662756262793216'}], 'text': 'RT @madeinmede: En conclusión, TODOS tienen covid pero unos dicen que es gripa y los otros ya se hicieron la prueba.', 'author_id': '1109237518501859328', 'created_at': '2021-12-31T05:09:59.000Z', 'id': '1476782666188038146'}, {'referenced_tweets': [{'type': 'retweeted', 'id': '1476629208382246914'}], 'text': 'RT @ufrj: UFRJ ainda exigirá comprovação vacinal contra covid-19 para acesso a espaços da Universidade.\nhttps://t.co/I6GvkbPOEk\n\n#ufrj #vac…', 'author_id': '995076839390547979', 'created_at': '2021-12-31T05:09:59.000Z', 'id': '1476782665248485395'}, {'referenced_tweets': [{'type': 'retweeted', 'id': '1476611444640735238'}], 'text': 'RT @NHSMillion: If everyone who has been grateful for NHS staff over the last two years followed and retweeted, we would reach a million in…', 'author_id': '704555058654883840', 'created_at': '2021-12-31T05:09:59.000Z', 'id': '1476782665047035904'}, {'referenced_tweets': [{'type': 'retweeted', 'id': '1476333265548156928'}], 'text': 'RT @KLVeritas: COVID-19 vaccine mandates “have to be repealed” as the vaccines are “still in research” and “people cannot be mandated to pa…', 'author_id': '1122014915735089152', 'created_at': '2021-12-31T05:09:59.000Z', 'id': '1476782664908611585'}, {'referenced_tweets': [{'type': 'retweeted', 'id': '1476282872583577610'}], 'text': 'RT @ClmBfQrTheStQrm: The latest VAERS covid vaccine ‘adverse event’ reports stats have been published. When we consider that maybe 1% of al…', 'author_id': '1378566968253513729', 'created_at': '2021-12-31T05:09:59.000Z', 'id': '1476782664447373330'}, {'referenced_tweets': [{'type': 'retweeted', 'id': '1476679233254612994'}], 'text': 'RT @Julioac13: Polémico festejo de Fin de Año en la Afip: 160 contagiados con Covid. LN+', 'author_id': '1190492803366838272', 'created_at': '2021-12-31T05:09:59.000Z', 'id': '1476782664275447810'}], 'includes': {'users': [{'name': "julie't", 'id': '4687651890', 'location': 'Rio Tercero', 'username': 'juliettapereyra', 'verified': False}, {'name': 'Emily 💕', 'id': '1001136081994174464', 'location': 'ur moms house', 'username': 'appl3ofyoureye', 'verified': False}, {'name': 'nαdaaaa', 'id': '1043168694963200001', 'location': 'Japan', 'username': 'Nadashadow3', 'verified': False}, {'name': '.', 'id': '1257280909', 'username': 'angel_canelones', 'verified': False}, {'name': 'ᴳᵒᵐᵉⁿᵉᵃ☃️', 'id': '1109237518501859328', 'username': 'wtfisthat23_', 'verified': False}, {'name': 'Marins', 'id': '995076839390547979', 'location': 'Saquarema, Brasil', 'username': 'joaomarinx', 'verified': False}, {'name': 'Tracey', 'id': '704555058654883840', 'location': 'Austral, Sydney', 'username': 'traceyaustralia', 'verified': False}, {'name': 'LetFreedomRing', 'id': '1122014915735089152', 'username': 'Konsiderthis', 'verified': False}, {'name': 'CrystalS.', 'id': '1378566968253513729', 'location': 'NH', 'username': 'CrystalSURFgrl', 'verified': False}, {'name': 'Marité Moyano', 'id': '1190492803366838272', 'location': 'Ciudad Autónoma de Buenos Aire', 'username': 'MoyanoMarite', 'verified': False}], 'tweets': [{'text': 'plata, covid, y suerte en el amor nunca tuve', 'author_id': '2800469738', 'created_at': '2021-12-29T16:31:23.000Z', 'id': '1476229371308363777'}, {'text': '“I’m here for a good time, not a long time” between Covid and climate change, you’re here for neither', 'author_id': '1022128903236800512', 'created_at': '2021-12-30T13:29:24.000Z', 'id': '1476545960767598592'}, {'text': 'quebec will really let someone positive for covid work but not someone wearing a hijab lol', 'author_id': '4390003996', 'created_at': '2021-12-29T08:29:16.000Z', 'id': '1476108039468077057'}, {'text': 'Totalmente de acuerdo con empezar a pedir el certificado de vacunación para ir a lugares públicos. Poner en riesgo a otros por ser antivacunas no es justo. Eso no es perder la libertad. Perder la libertad es terminar internado o muerto por un par de egoístas.', 'author_id': '328312757', 'created_at': '2021-12-29T19:41:15.000Z', 'id': '1476277152068689920'}, {'text': 'En conclusión, TODOS tienen covid pero unos dicen que es gripa y los otros ya se hicieron la prueba.', 'author_id': '823595958525116417', 'created_at': '2021-12-30T21:13:30.000Z', 'id': '1476662756262793216'}, {'text': 'UFRJ ainda exigirá comprovação vacinal contra covid-19 para acesso a espaços da Universidade.\nhttps://t.co/I6GvkbPOEk\n\n#ufrj #vacina #covid19 https://t.co/Dd79rutNDn', 'author_id': '38733808', 'created_at': '2021-12-30T19:00:12.000Z', 'id': '1476629208382246914'}, {'text': 'If everyone who has been grateful for NHS staff over the last two years followed and retweeted, we would reach a million in no time.\n\nIt will only take a few seconds, and your support would really mean a lot to a huge number of people who continue to fight Covid-19. https://t.co/q3UHkk82Rc', 'author_id': '4882743003', 'created_at': '2021-12-30T17:49:37.000Z', 'id': '1476611444640735238'}, {'text': 'COVID-19 vaccine mandates “have to be repealed” as the vaccines are “still in research” and “people cannot be mandated to participate in research,” says\xa0@P_McCulloughMD \nhttps://t.co/ReBmW1uNfm', 'author_id': '1443993685209673729', 'created_at': '2021-12-29T23:24:14.000Z', 'id': '1476333265548156928'}, {'text': 'The latest VAERS covid vaccine ‘adverse event’ reports stats have been published. When we consider that maybe 1% of all reports make it to the list, you can add two zero’s onto each number, making for uncomfortable reading... https://t.co/MxpH1eKo2t', 'author_id': '1460273925020168197', 'created_at': '2021-12-29T20:03:59.000Z', 'id': '1476282872583577610'}, {'text': 'Polémico festejo de Fin de Año en la Afip: 160 contagiados con Covid. LN+', 'author_id': '1373021228043276290', 'created_at': '2021-12-30T22:18:59.000Z', 'id': '1476679233254612994'}]}, 'meta': {'newest_id': '1476782667920121858', 'oldest_id': '1476782664275447810', 'result_count': 10, 'next_token': 'b26v89c19zqg8o3fpe17velvouuzga5en99sdltam89kt'}}
[2021-12-31 23:35:18,181] {python.py:175} INFO - Done. Returned value was: None
[2021-12-31 23:35:18,196] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=load_dimensions, task_id=tweet_extraction, execution_date=20211231T050000, start_date=20211231T233517, end_date=20211231T233518
[2021-12-31 23:35:18,222] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-31 23:35:18,257] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
